### ISSUE TITLE
QIVIVE models

### ISSUE THREAD

**Issue by PARODBE** [USEPA/CompTox-ExpoCast-httk#10]
Hi,

I am not an expert in pbpk models, could you help me to build a qivive model? Could it be possible do it for drugs which they are not included in this library? Like a test set...thanks!

**Comment by jfwambaugh** [comment]
Hello, the R package includes several pre-built PBPK models that can be used for QIVIVE. The function calc_mc_oral_equivalent will let you perform steady-state QIVIVE (assuming the subject is in equilibrium with their chemical exposure). However, dynamic QIVIVE can be performed using solve_model functions like solve_pbtk, solve_gas_pbtk, and solve_fetla_pbtk. All the models work with a library of ~1000 chemicals with in vitro data and phys-chem properties. These data include many drugs.

If you wish to add additional data you can use the function add_chemtable. See help(add_chemtable) for the full instructions.

This R package is not yet all that easy to use for building new PBPK/QIVIVE models, however that is also possible if you program in C or MCSim. We are working on a paper documenting how someone can more easily add new models, but to date all the models have been added by researchers working closely with the US EPA.
