### ISSUE TITLE
The "calc_hep_clearance" function adjusts "Clint" two times.

### ISSUE THREAD

**Issue by t-anton** [USEPA/CompTox-ExpoCast-httk#13]
It seems that the "calc_hep_clearance" function adjusts "Clint" two times for a fraction of chemical unbound in in vitro hepatocyte assay. Please see a reproducible example below: 

# REPRODUCIBLE EXAMPLE:
# The example has two parts. The first part, 
# "1. CURRENT IMPLEMENTATION", shows current calculations, and the second part, 
# "2. FIX: Set "adjusted.Clint = FALSE" (see line 55) ", which proposes a fix. 
# However, I have found this bug in one part of the code, but it may be present in other parts.
# The "calc_hep_clearance" code should be inspected to check if there are more instances where the adjustment is done two times. 
# I would start by looking at how many times "parameterize_steadystate" is called in the function and confirm that attribute "adjust.Clint" is set correctly.

library(httk)
packageVersion("httk")

load_sipes2017(overwrite = TRUE, target.env = .GlobalEnv)

#############################
# 1. CURRENT IMPLEMENTATION #
#############################

# 1.1 Current hepatic clearance result from HTTK's "calc_hep_clearance" function"
Clint_httk_result = calc_hep_clearance(chem.cas = '107-02-8', species = 'Human', hepatic.model = "unscaled")

# 1.2 Calculation of hepatic clearance by hand using the current implementation.
## Parameters for calculation. 
parameters <- parameterize_steadystate(chem.cas = '107-02-8',
                                       species = 'Human', 
                                       adjusted.Funbound.plasma = FALSE, 
                                       adjusted.Clint = TRUE, # This argument is set to "TRUE" in the current current implementation, so Clint is adjusted for fraction of chemical unbound in in vitro hepatocyte assay.
                                       suppress.messages = TRUE)

Clint_currently_implemented = parameters$Clint
# Correct for fraction of chemical unbound in in vitro hepatocyte assay ad in
# Kilford et al. (2008) (and used by Wetmore et al. (2015):
fu_hep = parameters$Fhep.assay.correction
Clint_currently_implemented <- Clint_currently_implemented / fu_hep # Clint is adjusted for the second time! This is where error is introduced.
## Convert from uL/min/10^6 cells to uL/min/g-liver to uL/min/kg BW
Clint_currently_implemented = Clint_currently_implemented*parameters$million.cells.per.gliver
## Convert from uL/min/g-liver to uL/min/kg BW
Clint_currently_implemented = Clint_currently_implemented*(parameters$Vliverc*1000*parameters$liver.density)
## Convert from uL/min/kg BW to L/h/kg BW
Clint_currently_implemented = Clint_currently_implemented/10^6*60 
## For "unscaled" model
Clint_currently_implemented <- Clint_currently_implemented

######################################################
# 2. FIX: Set "adjusted.Clint = FALSE" (see line 55) #
######################################################

# ADMET_Predictor(as reported in load_sipes2017)
Clint_ADMET_Predictor = as.numeric(chem.physical_and_invitro.data[chem.physical_and_invitro.data$CAS=='107-02-8',"Human.Clint"])

# 2.1 Calculation of hepatic clearance by hand
## Parameters for calculation 
parameters <- parameterize_steadystate(chem.cas = '107-02-8',
                                       species = 'Human', 
                                       adjusted.Funbound.plasma = FALSE, 
                                       adjusted.Clint = FALSE, # THIS IS A CORRECT FIX! It is "TRUE" in the current implementation (see line 26), which is where the bug is introduced.
                                       suppress.messages = TRUE)

Clint = parameters$Clint
# Correct for fraction of chemical unbound in in vitro hepatocyte assay ad in
# Kilford et al. (2008) (and used by Wetmore et al. (2015):
fu_hep = parameters$Fhep.assay.correction
Clint <- Clint / fu_hep
## Convert from uL/min/10^6 cells to uL/min/g-liver to uL/min/kg BW
Clint = Clint*parameters$million.cells.per.gliver
## Convert from uL/min/g-liver to uL/min/kg BW
Clint = Clint*(parameters$Vliverc*1000*parameters$liver.density)
## Convert from uL/min/kg BW to L/h/kg BW
Clint = Clint/10^6*60 
## For "unscaled" model
CLh <- Clint

# COMPARISON
cat('Clint_httk_result: ',Clint_httk_result,'\n')
cat('Clint_currently_implemented: ',Clint_currently_implemented,'\n')
cat('Clint_ADMET_Predictor: ',Clint_ADMET_Predictor,'\n')
cat('CLh: ',CLh,'\n')
[Clint calculations in HTTK.TXT](https://github.com/USEPA/CompTox-ExpoCast-httk/files/10069175/Clint.calculations.in.HTTK.TXT)

**Comment by jfwambaugh** [comment]
This is a great catch, Todor. Thank you so much!

What I have done is remove the second adjustment for fu_hep from calc_hep_clearance. That way the user can still turn off the adjustment if they want using the "adjusted.clint" argument. So now the adjustment only occurs in parameterization functions. I have also added a new function 'apply_clint_adjustment' to standardize implementation of the adjustment. There wasn't really a problem that I observed, but we're trying to eliminate duplication of code. The results don't seem to have changed too much, but what we had before was clearly incorrect. 

Look for all of this in the next release. Fantastic help!

**Comment by t-anton** [comment]
Hi John,

Thanks for your reply.
I worked on a project which needed hepatic clearance calculations, so I did
the first few chemicals by hand. Then I realized that httk could do the
same thing quicker, but when I got different results, I started to dig more
:). BTW, I will apply the same fix on my side as well.

Looking forward to the next release.

Best,

Todor
