### ISSUE TITLE
Using mc_oral_equiv

### ISSUE THREAD

**Issue by PARODBE** [USEPA/CompTox-ExpoCast-httk#14]
Hi,

It would be great if you could help me with a question. I am using your library to obtain in vivo doses from in vitro concentracions. My question is, as the majority of the my compounds are not present in the httk dataset, I am using add_chematable function adding LogP, MW, Fub, Clint. I can use calc_mc_oral_equiv function for obtaining my IVIVE model, and I don't obtain errors, although sometimes httk doesn't compute anything. Is this correct or I should add more information to my new compounds?

Thanks
Pablo

**Comment by jfwambaugh** [comment]
Hello Pablo -- I apologize for the delay in responding. Without specific examples I am not entirely sure why httk is giving you values sometimes but not others. However, one thing that could be going on is that some chemicals may be filtered on the basis of being inappropriate for a given model. For example, the model "3compartmentss" does not include exhalation, so highly volatile chemicals are filtered out be default.

After using add_chemtable to add data, you can use get_cheminfo(model="MODEL") to see if your new chemicals are now available. If some but not all show up, it's likely the filters got them.

John
