### ISSUE TITLE
Simplify calling `create_mc_samples()` with user-supplied `httkpop.dt`

### ISSUE THREAD

**Issue by carolinering** [USEPA/CompTox-ExpoCast-httk#19]
Thanks to En-Hsuan Lu (Texas A&M University) for identifying this issue!

httk version 2.2.2: In order to have `create_mc_samples()` use a user-supplied `httkpop.dt` (user-supplied table of population physiology samples), you have to ensure that you have specified `httkpop = TRUE` and specify the argument `samples` equal to the number of rows in the user-supplied `httkpop.dt`.  

I suggest that the user should only have to specify `httkpop.dt` and the other arguments should be automatically set accordingly.

Reproducible example:

First create a table of population physiology using `httkpop_generate()`
```
library(httk)
library(data.table)

set.seed(42) #for reproducibility

#Generate population physiology using httk-pop
DT_pop <- httk::httkpop_generate(method = "d", #direct resampling
                            nsamp = 200, #number of individuals
                            agelim_years = c(18,79))
```

Now, call `create_mc_samples()`, supplying `httkpop.dt = DT_pop` . 

# If you specify `httkpop = FALSE`

Dangerously, the following code does not produce an error or warning. Instead, it silently ignores the user-supplied `httkpop.dt` and produces output that holds physiology variables constant.

```
DT_mc <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop,
                                 httkpop = FALSE)
head(DT_pop) #note that physiology variables Qcardiacc and following are all constant -- DT_pop has been ignored
```

# If you specify `httkpop = TRUE` but do not specify `samples`

The following code produces an error:

```
DT_mc <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop,
                                 httkpop = TRUE)
```

This code produces the following error:

```
Error in `[.data.table`(parameters.dt, , `:=`(names(physiology.dt), physiology.dt)) : 
  Supplied 200 items to be assigned to 1000 items of column 'million.cells.per.gliver'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
```
I suggest that if a user specifies `httkpop.dt`, then `samples` should automatically be set to `nrow(httkpop.dt)`, rather than requiring the user to specify.

# To make `create_mc_samples()` use a user-supplied `httkpop.dt` as intended

You have to explicitly specify a value for `samples` , giving the number of rows in `DT_pop`. (`httkpop = TRUE` is the default, so you don't have to explicitly specify that argument.)

```
DT_mc <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop,
                                 samples = nrow(DT_pop))
head(DT_mc) #note that physiology variables Qcardiacc and following reflect population variability
```

To confirm that `create_mc_samples()` is using the user-supplied `DT_pop` rather than generating a new simulated population, repeat the call and confirm that the physiology variables are the same as before (variables `Qcardiacc` and following, except for `Rblood2plasma`, which is not expected to be the same). If `create_mc_samples()` were randomly generating a new simulated population, the physiology variables would be different for the second call.

```
DT_mc2 <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop,
                                 samples = nrow(DT_pop))
sapply(names(DT_mc2)[24:36], function(x) all.equal(DT_mc[[x]], DT_mc2[[x]])) #all TRUE except for Rblood2plasma, as expected
```

# Suggested behavior

I suggest that the following code chunk should be all that is needed to call `create_mc_samples()` with user-supplied `httkpop.dt`:

```
DT_mc <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop)
```

I also suggest that if a user specifies `httkpop.dt` and also specifies `httkpop = FALSE`, then `httkpop` should be changed to `TRUE` (with a warning) so that the user-supplied `httkpop.dt` is used.

```
DT_mc <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop,
                                  httkpop = FALSE)
#Suggest a warning like "Warning: httkpop = FALSE but a value for httkpop.dt was supplied. Setting httkpop = TRUE to use the user-supplied httkpop.dt", but the output should be the same as the above code chunk.
```

**Comment by jfwambaugh** [comment]
The following now works:
library(httk)
library(data.table)
set.seed(42) #for reproducibility
#Generate population physiology using httk-pop
DT_pop <- httk::httkpop_generate(method = "d", #direct resampling
                            nsamp = 200, #number of individuals
                            agelim_years = c(18,79))
DT_mc <- httk::create_mc_samples(chem.name = "Bisphenol-A",
                                 model = "pbtk", 
                                 httkpop.dt = DT_pop,
                                 httkpop = TRUE)
Warning messages:
1: In httk::create_mc_samples(chem.name = "Bisphenol-A", model = "pbtk",  :
  samples set to 200 to match number of rows in httkpop.dt supplied as argument

**Comment by jfwambaugh** [comment]
Everything but warning now in 2.4.0.
